spring.application.name=SocialMedia
spring.datasource.username=socialmedia_springboot_user
spring.datasource.password=wKqI2dBHJYTosJJtYWt1wQuKjrsMD4bJ
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d829vibeo5us73873jjg-a.oregon-postgres.render.com/socialmedia_springboot?currentSchema-public
server.port=8080